# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cost', models.IntegerField(blank=True, default=0)),
                ('one_cost', models.IntegerField(blank=True, default=0)),
                ('two_cost', models.IntegerField(blank=True, default=0)),
                ('three_cost', models.IntegerField(blank=True, default=0)),
                ('four_cost', models.IntegerField(blank=True, default=0)),
                ('five_cost', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LastAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'datetime',
            },
        ),
        migrations.CreateModel(
            name='monthMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('one', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
                ('four', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
