# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statisticsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
                ('four', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=1000)),
                ('one_amount', models.IntegerField(default=0)),
                ('two_amount', models.IntegerField(default=0)),
                ('three_amount', models.IntegerField(default=0)),
                ('four_amount', models.IntegerField(default=0)),
                ('five_amount', models.IntegerField(default=0)),
                ('amount_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
