# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0002_statisticsmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банк'},
        ),
        migrations.AlterModelOptions(
            name='costs',
            options={'verbose_name': 'Трата', 'verbose_name_plural': 'Траты'},
        ),
        migrations.AlterModelOptions(
            name='lastaction',
            options={'get_latest_by': 'datetime', 'verbose_name': 'Последнее действие', 'verbose_name_plural': 'Последние действия'},
        ),
        migrations.AlterModelOptions(
            name='monthmoney',
            options={'verbose_name': 'Месячные деньги', 'verbose_name_plural': 'Месячные деньги'},
        ),
        migrations.AlterModelOptions(
            name='statisticsmonth',
            options={'verbose_name': 'Месячная статистика', 'verbose_name_plural': 'Месячная статистика'},
        ),
        migrations.AlterField(
            model_name='monthmoney',
            name='date',
            field=models.DateField(),
        ),
    ]
