# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0003_auto_20171020_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthmoney',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
