# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 15:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('tittle', models.CharField(max_length=45)),
                ('text', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('Программирование', 'Программирование'), ('Жизнь', 'Жизнь')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='post')),
            ],
        ),
    ]
