# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20171027_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name_url',
            field=models.CharField(max_length=45),
        ),
    ]
