# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20171027_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='admin', max_length=45),
            preserve_default=False,
        ),
    ]
