# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('programming', 'Программирование'), ('life', 'Жизнь'), ('baby', 'Малыш'), ('ali', 'Алиэкспресс'), ('thoughts', 'Мысли'), ('recipes', 'Рецепты')], max_length=20),
        ),
    ]
