# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20171031_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='look',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
