# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_post_look'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('username_on_comp', models.CharField(blank=True, max_length=200)),
                ('browser', models.CharField(blank=True, max_length=500)),
                ('last_time_in_sec', models.IntegerField()),
            ],
        ),
    ]
