# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_informationsclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsclient',
            name='last_time_in_sec',
        ),
        migrations.AddField(
            model_name='informationsclient',
            name='last_time',
            field=models.IntegerField(default=0),
        ),
    ]
