# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20171104_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsclient',
            name='last_time',
            field=models.DateTimeField(),
        ),
    ]
