# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20171104_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsclient',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
