# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20171104_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsclient',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='informationsclient',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='informationsclient',
            name='username_on_comp',
        ),
        migrations.AddField(
            model_name='informationsclient',
            name='name_url',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
