# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('volume', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('toilet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BabyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('lenght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.IntegerField()),
                ('total_toilet', models.IntegerField()),
                ('data', models.DateField(auto_now=True)),
                ('days', models.CharField(max_length=7)),
            ],
        ),
    ]
