# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babyeat',
            options={'verbose_name': 'Таблица питания', 'verbose_name_plural': 'Таблица питания'},
        ),
        migrations.AlterModelOptions(
            name='babyweight',
            options={'verbose_name': 'Развитие малыша', 'verbose_name_plural': 'Развитие малыша'},
        ),
        migrations.AlterModelOptions(
            name='historyeat',
            options={'verbose_name': 'История питания', 'verbose_name_plural': 'История питания'},
        ),
    ]
