# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baby', '0002_auto_20171020_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyeat',
            name='toilet',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
