# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baby', '0003_auto_20180101_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyeat',
            name='toilet',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
    ]
