# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baby', '0005_auto_20180101_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyeat',
            name='toilet',
            field=models.BooleanField(default=False),
        ),
    ]
